services:
  postgres:
    image: postgres:latest
    container_name: postgres_db_twin
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: twin
    volumes:
      - ./postgres_data_twin:/var/lib/postgresql/data
    ports:
      - "45432:5432"

volumes:
  postgres_data:


  #todo Zet de goede yml die in de cloud staat hierin om problemen te verkomen