spring.application.name=DigitalTwinDashboard

# Database verbinding
spring.datasource.url=jdbc:postgresql://localhost:45432/twin
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA instellingen
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
